version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=notifications_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    #ports:
    #- '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    #ports:
    #- '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
  api:
    container_name: notifications-api
    build:
      context: ./
    image: notifications-api
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: notifications_api_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - db
      - redis
volumes:
  db:
    driver: local
  redis:
    driver: local
